language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt


# command to run tests.py
script: 
  - nosetests --exe -v
  - nosetests --with-coverage --exe --cover-inclusive --cover-package=app
  - coveralls

after_sucess:
  - "coveralls"
