language: python
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt


# command to run tests.py
script: 
  - nosetests tests.py
  - python manage.py cov
  - coverage run tests.py
  - coveralls
